config/routes.rb
Rails.application.routes.draw do
  
  
  get 'about-us', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'admin', to: 'static_pages#admin'
  get 'member', to: 'static_pages#member'
  
  root to: 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def admin
  end

  def member
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


	  def nav_items
    [
      {
        url: root_path,
        title: 'Home'
      },

      {
        url: contact_path,
        title: 'Contact'
      },
      {
        url: about_us_path,
        title: 'About'
      },
    
    ]
  end
  
 def nav_helper style, tag_type
    nav_links = ''

    nav_items.each do |item|
      nav_links << "<#{tag_type}><a href='#{item[:url]}' class='#{style} #{active? item[:url]}'>#{item[:title]}</a></#{tag_type}>"
    end

    nav_links.html_safe
  end

  def active? path
    "active" if current_page? path
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OmosPortal</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

       <div id="background"></div>

       
   <%= render "shared/application_nav" %>
         
       

  	
    <%= yield %>

  <%= render "shared/application_footer" %>





        </div>

      </div>

    </div>
  </body>
</html>

app/views/shared/_application_footer.html.erb
 <div class="mastfoot">
            <div class="inner">
              <p>Omos Portal v 1.0 </p>
            </div>
          </div>

app/views/shared/_application_nav.html.erb
   <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Omos-Portal v1.0</h3>
              <nav class="nav nav-masthead app-nav">
                <%= nav_helper 'nav-link', 'span' %>
                
                
              </nav>
            </div>
          </div>
       


     

app/views/static_pages/about.html.erb
<div class="card">
 
  <div class="card-block">
    <h4 class="card-title">About the OMOS project</h4>
    <p class="card-text">You will soon find out the Vision of the OMOS project</p>
    <a href="#" class="btn btn-primary">Learn more</a>
  </div>
   <span class="badge badge-danger">Portal under construction !!!</span>
</div>

app/views/static_pages/admin.html.erb
 <h1 class="cover-heading">Welcome to the Admin Portal</h1>
 <span class="badge badge-danger">Portal under construction !!!</span>

 <%= link_to "Click here to go back", root_path %>

app/views/static_pages/contact.html.erb
<div class="card">
 <div class="row">
 	<div class="col-md-6">
  <div class="card-block">
    <h4 class="card-title">Contact</h4>
    <p class="card-text">Please contact the IT Department</p>
    <a href="#" class="btn btn-primary">Contact</a>
  </div>
</div>

  <div class="col-md-6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3971.0754104101834!2d-0.22881528651424557!3d5.5558401351990945!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdf975379c5f337%3A0x8f2686e1d6774d76!2sICGC+christ+temple!5e0!3m2!1sen!2sgh!4v1509696080201" width="300" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
    </div>
     <span class="badge badge-danger">Portal under construction !!!</span>
</div>



app/views/static_pages/home.html.erb
   <div class="inner cover">
            <h1 class="cover-heading">Welcome to the OMOS Portal</h1>
            <span class="badge badge-danger">Portal under construction !!!</span>
            <p class="lead"> Our vision for the year 2017 is to win a soul , one member at a time</p>
            <p class="lead">
              
              <%= link_to "Administrator", admin_path, class: "btn btn-lg btn-secondary" %>
            </p>

             <p class="lead">
              <%= link_to "Member", member_path, class: "btn btn-lg btn-secondary" %>
            </p>
          </div>

app/views/static_pages/member.html.erb
 <h1 class="cover-heading">Welcome to the Member Section</h1>
  <span class="badge badge-danger">Portal under construction !!!</span>
  <%= link_to "Click here to go back ", root_path %>